import Link from "next/link";
import { money, shortDate } from "@/lib/format";
import type { PaymentView } from "@/lib/payments-view";

export type PaymentRow = { id: string; status?: string | null; amount_usd?: number | null; amount_lbp?: number | null; method?: string | null; uploaded_at?: string | null; confirmed_at?: string | null; reviewed_at?: string | null; payment_date?: string | null; voided_at?: string | null; reviewer_decision_note?: string | null; receipt_token?: string | null; receipt_url?: string | null; invoice_id: string; invoices?: { title?: string | null; invoice_number?: string | null; clients?: { name?: string | null } | null } | null };
const empty: Record<PaymentView, string> = { awaiting: "No proofs waiting for review", approved: "No approved payments yet", rejected: "No rejected proofs", manual: "No manual payments recorded", receipts: "No receipts issued", history: "No payment activity yet" };

export function PaymentsView({ view, rows }: { view: PaymentView; rows: PaymentRow[] }) {
  if (!rows.length) return <div className="rounded-2xl border border-slate-200 bg-white p-10 text-center text-sm text-slate-600">{empty[view]}</div>;
  return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="divide-y divide-slate-100">{rows.map((payment) => {
    const invoice = payment.invoices;
    const date = payment.voided_at || payment.confirmed_at || payment.reviewed_at || payment.payment_date || payment.uploaded_at;
    return <article key={payment.id} className="grid min-w-0 gap-4 p-4 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><div className="min-w-0"><p className="break-words font-semibold text-ink">{invoice?.invoice_number || invoice?.title || "Invoice"}</p><dl className="mt-2 grid gap-2 text-sm text-slate-600 sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-xs font-semibold text-slate-500">Client</dt><dd className="break-words">{invoice?.clients?.name || "Client"}</dd></div><div><dt className="text-xs font-semibold text-slate-500">Amount</dt><dd className="font-semibold text-ink">{payment.amount_usd ? money(Number(payment.amount_usd), "USD") : "—"}{payment.amount_usd && payment.amount_lbp ? " · " : ""}{payment.amount_lbp ? money(Number(payment.amount_lbp), "LBP") : ""}</dd></div><div><dt className="text-xs font-semibold text-slate-500">Method</dt><dd className="break-words">{payment.method || "Payment"}</dd></div><div><dt className="text-xs font-semibold text-slate-500">Status and date</dt><dd className="break-words">{payment.voided_at ? "Voided" : payment.status || "Unknown"} · {date ? shortDate(date) : "—"}</dd></div></dl>{payment.reviewer_decision_note ? <p className="mt-2 break-words text-xs text-slate-500">{payment.reviewer_decision_note}</p> : null}</div><div className="flex flex-wrap gap-2"><Link className="btn btn-secondary text-xs" href={`/invoices/${payment.invoice_id}`}>Open invoice</Link>{payment.receipt_url ? <Link className="btn btn-secondary text-xs" href={payment.receipt_url} target="_blank">Open receipt</Link> : null}</div></article>;
  })}</div></section>;
}